// <auto-generated />
using System;
using MembershipPortal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MembershipPortal.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20211112141806_newaddsinitial")]
    partial class newaddsinitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MembershipPortal.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MemberId");

                    b.Property<string>("academicRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("academicTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateofBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("memberAge");

                    b.Property<string>("fieldofStudy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("hostInstitution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("interestArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lasttName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("memberCVURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memberCertificateURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memberPhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("refrencePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("speciality")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("refrencePersonId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MembershipPortal.Models.Member", b =>
                {
                    b.HasOne("MembershipPortal.Models.Member", "refrencePerson")
                        .WithMany()
                        .HasForeignKey("refrencePersonId");

                    b.Navigation("refrencePerson");
                });
#pragma warning restore 612, 618
        }
    }
}
