// <auto-generated />
using System;
using MembershipPortal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MembershipPortal.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20211108200623_UpdateRelationship")]
    partial class UpdateRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MembershipPortal.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MemberId");

                    b.Property<string>("academicRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("academicTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateofBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("memberAge");

                    b.Property<string>("fieldofStudy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("hostInstitution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("interestArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lasttName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("memberCVURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memberCertificateURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memberPhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("refrencePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("speciality")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("refrencePersonId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            academicRank = "MSc.",
                            academicTitle = "Lecturer",
                            city = "Adama",
                            dateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fieldofStudy = "Computer Science",
                            firstName = "Anwar",
                            gender = "Male",
                            lasttName = "Hussein",
                            middleName = "Bilcha",
                            speciality = "Software Engineering"
                        },
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991987"),
                            academicRank = "BSc.",
                            academicTitle = "Engineer",
                            city = "Adama",
                            dateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fieldofStudy = "Civil Engineering",
                            firstName = "Nebilr",
                            gender = "Male",
                            lasttName = "Abawari",
                            middleName = "Nuru",
                            speciality = "Civil Engineering"
                        });
                });

            modelBuilder.Entity("MembershipPortal.Models.Publication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PublicationId");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("coAuthors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("contributingMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("pubDOI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pubSubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("publicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("pubwebLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("MembershipPortal.Models.Member", b =>
                {
                    b.HasOne("MembershipPortal.Models.Member", "refrencePerson")
                        .WithMany()
                        .HasForeignKey("refrencePersonId");

                    b.Navigation("refrencePerson");
                });

            modelBuilder.Entity("MembershipPortal.Models.Publication", b =>
                {
                    b.HasOne("MembershipPortal.Models.Member", null)
                        .WithMany("memberPublications")
                        .HasForeignKey("MemberId");
                });

            modelBuilder.Entity("MembershipPortal.Models.Member", b =>
                {
                    b.Navigation("memberPublications");
                });
#pragma warning restore 612, 618
        }
    }
}
